version: "3.0"

services:
  py_server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: testing/server:1.0
    networks: 
      - base_network
    ports:
      - "3000:3000"
    

  py_client:
    build:
      context: .
      dockerfile: client.Dockerfile
    image: testing/client:1.0
    networks: 
      - base_network
    depends_on:
      - py_server


networks:
  base_network:
